# ===== BASE DE DATOS SUPABASE IPv4 =====
spring.datasource.url=jdbc:postgresql://db.mzbvbmahplqjzhmtyfwx.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=0412
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


# ===== MAIL (Gmail) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=emersonmelara44@gmail.com
spring.mail.password=kbho wcoj vbzr aflq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== JWT =====
jwt.secret=lashesStudioSecretKey2024SuperSegura
jwt.expiration=86400000

# ===== PROFILES =====
spring.profiles.active=prod
