# Render Postgres DB
spring.datasource.url=jdbc:postgresql://dpg-d6qpbfk50q8c73bmrveg-a/lashes_db_2wrz
spring.datasource.username=lashes_db_2wrz_user
spring.datasource.password=YyMrjG3yLEPG3TzETfrB6oFrvRlMrZEq
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secret=lashesStudioSecretKey2024SuperSegura
jwt.expiration=86400000

# Email Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=emersonmelara44@gmail.com
spring.mail.password=kbho wcoj vbzr aflq
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Profile
spring.profiles.active=prod
