# Base de datos Supabase
spring.datasource.url=jdbc:postgresql://db.mzbvbmahplqjzhmtyfwx.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=$Elmp0412#.


# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# JWT (usa el mismo secret que tienes en local)
jwt.secret=TU_JWT_SECRET_AQUI
jwt.expiration=86400000

# Email (usa los mismos que tienes en local)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=emersonmelara44@gmail.com
spring.mail.password=admin0412
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
