# ===== BASE DE DATOS =====
spring.datasource.url=jdbc:postgresql://localhost:5432/lashes_db
spring.datasource.username=lashes_user
spring.datasource.password=lashes0412
spring.datasource.driver-class-name=org.postgresql.Driver

# ===== JPA / HIBERNATE =====
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===== SERVIDOR =====
server.port=8080

# ===== MAIL (Gmail) =====
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=TU_CORREO@gmail.com
spring.mail.password=TU_APP_PASSWORD
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===== JWT =====
jwt.secret=lashesStudioSecretKey2024SuperSegura
jwt.expiration=86400000

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.mail.MailSenderAutoConfiguration
